name: Run Python Job

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run Python
        run: |
          python parking_bot.py --headless